/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemorialRouteImport } from './routes/memorial'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as MapRouteImport } from './routes/map'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DailyLogRouteImport } from './routes/daily-log'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AsBuiltRouteImport } from './routes/as-built'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'

const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialRoute = MemorialRouteImport.update({
  id: '/memorial',
  path: '/memorial',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLogRoute = DailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AsBuiltRoute = AsBuiltRouteImport.update({
  id: '/as-built',
  path: '/as-built',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/as-built': typeof AsBuiltRoute
  '/budgets': typeof BudgetsRoute
  '/daily-log': typeof DailyLogRoute
  '/design-system': typeof DesignSystemRoute
  '/financial': typeof FinancialRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/measurements': typeof MeasurementsRoute
  '/memorial': typeof MemorialRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/as-built': typeof AsBuiltRoute
  '/budgets': typeof BudgetsRoute
  '/daily-log': typeof DailyLogRoute
  '/design-system': typeof DesignSystemRoute
  '/financial': typeof FinancialRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/measurements': typeof MeasurementsRoute
  '/memorial': typeof MemorialRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/as-built': typeof AsBuiltRoute
  '/budgets': typeof BudgetsRoute
  '/daily-log': typeof DailyLogRoute
  '/design-system': typeof DesignSystemRoute
  '/financial': typeof FinancialRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/measurements': typeof MeasurementsRoute
  '/memorial': typeof MemorialRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/as-built'
    | '/budgets'
    | '/daily-log'
    | '/design-system'
    | '/financial'
    | '/library'
    | '/map'
    | '/measurements'
    | '/memorial'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/standards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/as-built'
    | '/budgets'
    | '/daily-log'
    | '/design-system'
    | '/financial'
    | '/library'
    | '/map'
    | '/measurements'
    | '/memorial'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/standards'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/as-built'
    | '/budgets'
    | '/daily-log'
    | '/design-system'
    | '/financial'
    | '/library'
    | '/map'
    | '/measurements'
    | '/memorial'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/standards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AsBuiltRoute: typeof AsBuiltRoute
  BudgetsRoute: typeof BudgetsRoute
  DailyLogRoute: typeof DailyLogRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FinancialRoute: typeof FinancialRoute
  LibraryRoute: typeof LibraryRoute
  MapRoute: typeof MapRoute
  MeasurementsRoute: typeof MeasurementsRoute
  MemorialRoute: typeof MemorialRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  StandardsRoute: typeof StandardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial': {
      id: '/memorial'
      path: '/memorial'
      fullPath: '/memorial'
      preLoaderRoute: typeof MemorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-log': {
      id: '/daily-log'
      path: '/daily-log'
      fullPath: '/daily-log'
      preLoaderRoute: typeof DailyLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/as-built': {
      id: '/as-built'
      path: '/as-built'
      fullPath: '/as-built'
      preLoaderRoute: typeof AsBuiltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AsBuiltRoute: AsBuiltRoute,
  BudgetsRoute: BudgetsRoute,
  DailyLogRoute: DailyLogRoute,
  DesignSystemRoute: DesignSystemRoute,
  FinancialRoute: FinancialRoute,
  LibraryRoute: LibraryRoute,
  MapRoute: MapRoute,
  MeasurementsRoute: MeasurementsRoute,
  MemorialRoute: MemorialRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  StandardsRoute: StandardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
