/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'

const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/budgets': typeof BudgetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/budgets': typeof BudgetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/budgets': typeof BudgetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-assistant' | '/budgets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-assistant' | '/budgets'
  id: '__root__' | '/' | '/ai-assistant' | '/budgets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  BudgetsRoute: typeof BudgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  BudgetsRoute: BudgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
